from enum import Enum

VCF_SPECIFIC_HEADERS = [
    "#CHROM",
    "POS",
    "ID",
    "REF",
    "ALT",
    "QUAL",
    "FILTER",
    "INFO",
    "FORMAT",
]
VCF_SPECIFIC_HEADERS_INDEX = 8
VCF_FIRST_SAMPLE_ID_INDEX = 9
SNP_ID_INDEX = 2
FORMAT_INDEX = 9
INFO_INDEX = 8
FILTER_INDEX = 7


class InputType(str, Enum):
    BEAGLE = "beagle"
    ORDINARY_VCF = "ordinary_vcf"


class VCFGenotype(str, Enum):
    UNKNOWN = "./."
    HOMOZYGOUS_REFERENCE = "0/0"
    HETEROZYGOUS_1 = "1/0"
    HETEROZYGOUS_2 = "0/1"
    HOMOZYGOUS_ALTERNATIVE = "1/1"
    NOT_KNOWN_YET = "./1"
    NOT_KNOWN_YET_2 = "./0"

    BEAGLE_HOMOZYGOUS_REFERENCE = "0|0"
    BEAGLE_HETEROZYGOUS_1 = "1|0"
    BEAGLE_HETEROZYGOUS_2 = "0|1"
    BEAGLE_HOMOZYGOUS_ALTERNATIVE = "1|1"


class Genotype(str, Enum):
    UNKNOWN = "-1"
    HOMOZYGOUS_REFERENCE = "0"
    HETEROZYGOUS = "1"
    HOMOZYGOUS_ALTERNATIVE = "2"


VCF_GENOTYPE_TO_GENOTYPE = {
    VCFGenotype.UNKNOWN: Genotype.UNKNOWN,
    VCFGenotype.HOMOZYGOUS_REFERENCE: Genotype.HOMOZYGOUS_REFERENCE,
    VCFGenotype.HETEROZYGOUS_1: Genotype.HETEROZYGOUS,
    VCFGenotype.HETEROZYGOUS_2: Genotype.HETEROZYGOUS,
    VCFGenotype.HOMOZYGOUS_ALTERNATIVE: Genotype.HOMOZYGOUS_ALTERNATIVE,
    VCFGenotype.NOT_KNOWN_YET: Genotype.UNKNOWN,
    VCFGenotype.NOT_KNOWN_YET_2: Genotype.UNKNOWN,
    VCFGenotype.BEAGLE_HOMOZYGOUS_ALTERNATIVE: Genotype.HOMOZYGOUS_ALTERNATIVE,
    VCFGenotype.BEAGLE_HOMOZYGOUS_REFERENCE: Genotype.HOMOZYGOUS_REFERENCE,
    VCFGenotype.BEAGLE_HETEROZYGOUS_1: Genotype.HETEROZYGOUS,
    VCFGenotype.BEAGLE_HETEROZYGOUS_2: Genotype.HETEROZYGOUS,
}
